{
  "Header": {
    "Original": "CVE-2022-42969 (The py library through 1.11.0 for Python allows remote attackers to co ...)",
    "Line": 120545,
    "ID": "CVE-2022-42969",
    "Description": "(The py library through 1.11.0 for Python allows remote attackers to co ...)"
  },
  "Annotations": [
    {
      "Original": "- python-py \u003cunfixed\u003e (unimportant)",
      "Line": 120546,
      "Type": "package",
      "Package": "python-py",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/pytest-dev/py/issues/287",
      "Line": 120547,
      "Type": "NOTE",
      "Description": "https://github.com/pytest-dev/py/issues/287"
    },
    {
      "Original": "NOTE: Negligible security impact and disputed upstream",
      "Line": 120548,
      "Type": "NOTE",
      "Description": "Negligible security impact and disputed upstream"
    },
    {
      "Original": "NOTE: https://github.com/pytest-dev/py/issues/287#issuecomment-1283784766",
      "Line": 120549,
      "Type": "NOTE",
      "Description": "https://github.com/pytest-dev/py/issues/287#issuecomment-1283784766"
    }
  ]
}