{
  "Header": {
    "Original": "CVE-2018-16885 (A flaw was found in the Linux kernel that allows the userspace to call ...)",
    "Line": 384732,
    "ID": "CVE-2018-16885",
    "Description": "(A flaw was found in the Linux kernel that allows the userspace to call ...)"
  },
  "Annotations": [
    {
      "Original": "- linux 3.16.2-1",
      "Line": 384733,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "3.16.2-1"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1661503",
      "Line": 384734,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1661503"
    },
    {
      "Original": "NOTE: https://git.kernel.org/linus/06ebb06d49486676272a3c030bfeef4bd969a8e6",
      "Line": 384735,
      "Type": "NOTE",
      "Description": "https://git.kernel.org/linus/06ebb06d49486676272a3c030bfeef4bd969a8e6"
    }
  ]
}