{
  "Header": {
    "Original": "CVE-2014-3730 (The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, ...)",
    "Line": 552502,
    "ID": "CVE-2014-3730",
    "Description": "(The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-2934-1}",
      "Line": 552503,
      "Type": "xref",
      "Bugs": [
        "DSA-2934-1"
      ]
    },
    {
      "Original": "- python-django 1.6.5-1",
      "Line": 552504,
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "1.6.5-1"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/",
      "Line": 552505,
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/"
    }
  ]
}