{
  "Header": {
    "Original": "CVE-2020-28049 (An issue was discovered in SDDM before 0.19.0. It incorrectly starts t ...)",
    "Line": 246242,
    "ID": "CVE-2020-28049",
    "Description": "(An issue was discovered in SDDM before 0.19.0. It incorrectly starts t ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4783-1 DLA-2436-1}",
      "Line": 246243,
      "Type": "xref",
      "Bugs": [
        "DSA-4783-1",
        "DLA-2436-1"
      ]
    },
    {
      "Original": "- sddm 0.19.0-1 (bug #973748)",
      "Line": 246244,
      "Type": "package",
      "Package": "sddm",
      "Kind": "fixed",
      "Version": "0.19.0-1",
      "BugNo": 973748
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2020/11/04/2",
      "Line": 246245,
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2020/11/04/2"
    },
    {
      "Original": "NOTE: https://github.com/sddm/sddm/commit/be202f533ab98a684c6a007e8d5b4357846bc222",
      "Line": 246246,
      "Type": "NOTE",
      "Description": "https://github.com/sddm/sddm/commit/be202f533ab98a684c6a007e8d5b4357846bc222"
    },
    {
      "Original": "NOTE: https://bugzilla.suse.com/show_bug.cgi?id=1177201",
      "Line": 246247,
      "Type": "NOTE",
      "Description": "https://bugzilla.suse.com/show_bug.cgi?id=1177201"
    }
  ]
}