{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "PackageKit",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "PackageKit",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Will not fix",
      "package_name": "PackageKit",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2020-09-24T00:00:00Z",
  "bugzilla": {
    "description": "PackageKit: local attacker could use this issue to learn the MIME type of any file on the system",
    "id": "1884560",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1884560"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "2.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-200",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-16121",
  "document_distribution": "",
  "details": [
    "PackageKit provided detailed error messages to unprivileged callers that exposed information about file presence and mimetype of files that the user would be unable to determine on its own."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2020-16121\nhttps://nvd.nist.gov/vuln/detail/CVE-2020-16121\nhttps://bugs.launchpad.net/ubuntu/%2Bsource/packagekit/%2Bbug/1888887\nhttps://people.canonical.com/~ubuntu-security/cve/2020/CVE-2020-16121.html?_ga=2.191526435.887932068.1602011173-1206535791.1586737989"
  ]
}