{
  "affected_release": [
    {
      "product_name": "Red Hat Ansible Tower 3.6 for RHEL 7",
      "release_date": "2020-10-14T00:00:00Z",
      "advisory": "RHSA-2020:4255",
      "package": "ansible-tower-36/ansible-runner-rhel7:1.4.4-2",
      "cpe": "cpe:/a:redhat:ansible_tower:3.6::el7"
    },
    {
      "product_name": "Red Hat Ansible Tower 3.7 for RHEL 7",
      "release_date": "2020-10-14T00:00:00Z",
      "advisory": "RHSA-2020:4254",
      "package": "ansible-tower-37/ansible-runner-rhel7:1.4.6-2",
      "cpe": "cpe:/a:redhat:ansible_tower:3.7::el7"
    },
    {
      "product_name": "Red Hat Ansible Tower 3.7 for RHEL 7",
      "release_date": "2020-11-30T00:00:00Z",
      "advisory": "RHSA-2020:5249",
      "package": "ansible-tower-37/ansible-tower-rhel7:3.7.4-1",
      "cpe": "cpe:/a:redhat:ansible_tower:3.7::el7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2021-11-09T00:00:00Z",
      "advisory": "RHSA-2021:4162",
      "package": "python38:3.8-8050020210811101222.e3d35cca",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2021-11-09T00:00:00Z",
      "advisory": "RHSA-2021:4162",
      "package": "python38-devel:3.8-8050020210811101222.e3d35cca",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2021-11-09T00:00:00Z",
      "advisory": "RHSA-2021:4324",
      "package": "python-psutil-0:5.4.3-11.el8",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4.2",
      "release_date": "2020-07-01T00:00:00Z",
      "advisory": "RHSA-2020:2593",
      "package": "python-psutil-0:5.6.6-1.el7ar",
      "cpe": "cpe:/a:redhat:openshift:4.2::el7"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4.3",
      "release_date": "2020-06-23T00:00:00Z",
      "advisory": "RHSA-2020:2635",
      "package": "python-psutil-0:5.6.6-1.el7ar",
      "cpe": "cpe:/a:redhat:openshift:4.3::el7"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4.4",
      "release_date": "2020-06-22T00:00:00Z",
      "advisory": "RHSA-2020:2583",
      "package": "python-psutil-0:5.6.6-1.el7ar",
      "cpe": "cpe:/a:redhat:openshift:4.4::el7"
    },
    {
      "product_name": "Red Hat Satellite 6.9 for RHEL 7",
      "release_date": "2021-04-21T00:00:00Z",
      "advisory": "RHSA-2021:1313",
      "package": "python-psutil-0:5.7.2-2.el7sat",
      "cpe": "cpe:/a:redhat:satellite:6.9::el7"
    },
    {
      "product_name": "Red Hat Satellite 6.9 for RHEL 7",
      "release_date": "2021-04-21T00:00:00Z",
      "advisory": "RHSA-2021:1313",
      "package": "python-psutil-0:5.7.2-2.el7sat",
      "cpe": "cpe:/a:redhat:satellite_capsule:6.9::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-0:3.8.6-1.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-psutil-0:5.6.4-5.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-urllib3-0:1.25.7-6.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-0:3.8.6-1.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-psutil-0:5.6.4-5.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-urllib3-0:1.25.7-6.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-0:3.8.6-1.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-psutil-0:5.6.4-5.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS",
      "release_date": "2020-10-20T00:00:00Z",
      "advisory": "RHSA-2020:4299",
      "package": "rh-python38-python-urllib3-0:1.25.7-6.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    }
  ],
  "package_state": [
    {
      "product_name": "CloudForms Management Engine 5",
      "fix_state": "Will not fix",
      "package_name": "python2-psutil",
      "cpe": "cpe:/a:redhat:cloudforms_managementengine:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "python39:3.9/python-psutil",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "python-psutil",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10 (Newton)",
      "fix_state": "Will not fix",
      "package_name": "python-psutil",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Will not fix",
      "package_name": "python-psutil",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 14 (Rocky)",
      "fix_state": "Will not fix",
      "package_name": "python-psutil",
      "cpe": "cpe:/a:redhat:openstack:14"
    },
    {
      "product_name": "Red Hat OpenStack Platform 15 (Stein)",
      "fix_state": "Will not fix",
      "package_name": "python-psutil",
      "cpe": "cpe:/a:redhat:openstack:15"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Will not fix",
      "package_name": "python-psutil",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "python-psutil",
      "cpe": "cpe:/a:redhat:quay:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2019-11-07T00:00:00Z",
  "bugzilla": {
    "description": "python-psutil: Double free because of refcount mishandling",
    "id": "1772014",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1772014"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.0",
    "cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-416",
  "statement": "",
  "acknowledgement": "This issue was discovered by Riccardo Schirone (Red Hat).",
  "name": "CVE-2019-18874",
  "document_distribution": "",
  "details": [
    "psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.",
    "A double free issue has been discovered in python-psutil because of the mishandling of refcounts while converting system data into Python objects in functions like psutil_disk_partitions(), psutil_users(), psutil_net_if_addrs(), and others. In particular cases, a local attacker may be able to get code execution by manipulating system resources that python-psutil then tries to convert."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2019-18874\nhttps://nvd.nist.gov/vuln/detail/CVE-2019-18874"
  ]
}