{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 5 (Icehouse)",
      "fix_state": "Affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:5::el6"
    },
    {
      "product_name": "Red Hat OpenStack Platform 4",
      "fix_state": "Affected",
      "package_name": "Django14",
      "cpe": "cpe:/a:redhat:openstack:4"
    },
    {
      "product_name": "Red Hat Subscription Asset Manager",
      "fix_state": "Affected",
      "package_name": "Django",
      "cpe": "cpe:/a:rhel_sam:1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2014-08-20T00:00:00Z",
  "bugzilla": {
    "description": "Django: RemoteUserMiddleware session hijacking",
    "id": "1129954",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1129954"
  },
  "cvss": {
    "cvss_base_score": "5.8",
    "cvss_scoring_vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "Red Hat would like to thank upstream Django project for reporting this issue. Upstream acknowledges David Greisen as the original reporter.",
  "name": "CVE-2014-0482",
  "document_distribution": "",
  "details": [
    "The contrib.auth.middleware.RemoteUserMiddleware middleware in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3, when using the contrib.auth.backends.RemoteUserBackend backend, allows remote authenticated users to hijack web sessions via vectors related to the REMOTE_USER header."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2014-0482\nhttps://nvd.nist.gov/vuln/detail/CVE-2014-0482\nhttps://www.djangoproject.com/weblog/2014/aug/20/security/"
  ]
}