{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 5 (Icehouse)",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:5::el6"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 6 (Juno)",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:6"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2015-01-13T00:00:00Z",
  "bugzilla": {
    "description": "Django: database denial of service with ModelMultipleChoiceField",
    "id": "1179685",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1179685"
  },
  "cvss": {
    "cvss_base_score": "4.3",
    "cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "Red Hat would like to thank upstream Django project for reporting this issue.",
  "name": "CVE-2015-0222",
  "document_distribution": "",
  "details": [
    "ModelMultipleChoiceField in Django 1.6.x before 1.6.10 and 1.7.x before 1.7.3, when show_hidden_initial is set to True, allows remote attackers to cause a denial of service by submitting duplicate values, which triggers a large number of SQL queries."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2015-0222\nhttps://nvd.nist.gov/vuln/detail/CVE-2015-0222\nhttps://www.djangoproject.com/weblog/2015/jan/13/security/"
  ]
}