{
  "affected_release": [
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "release_date": "2022-12-07T00:00:00Z",
      "advisory": "RHSA-2022:8863",
      "package": "python-paramiko-0:2.4.2-8.el8ost",
      "cpe": "cpe:/a:redhat:openstack:16.1::el8"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "release_date": "2022-12-07T00:00:00Z",
      "advisory": "RHSA-2022:8845",
      "package": "python-paramiko-0:2.4.2-8.el8ost",
      "cpe": "cpe:/a:redhat:openstack:16.2::el8"
    },
    {
      "product_name": "Red Hat Virtualization 4 for Red Hat Enterprise Linux 8",
      "release_date": "2022-05-26T00:00:00Z",
      "advisory": "RHSA-2022:4712",
      "package": "python-paramiko-0:2.4.3-3.el8ev",
      "cpe": "cpe:/o:redhat:rhev_hypervisor:4.4::el8"
    },
    {
      "product_name": "Red Hat Virtualization Engine 4.4",
      "release_date": "2022-05-26T00:00:00Z",
      "advisory": "RHSA-2022:4712",
      "package": "python-paramiko-0:2.4.3-3.el8ev",
      "cpe": "cpe:/a:redhat:rhev_manager:4.4:el8"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "paramiko",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ceph Storage 2",
      "fix_state": "Out of support scope",
      "package_name": "python-paramiko",
      "cpe": "cpe:/a:redhat:ceph_storage:2"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "python-paramiko",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-paramiko",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Storage 3",
      "fix_state": "Will not fix",
      "package_name": "python-paramiko",
      "cpe": "cpe:/a:redhat:storage:3"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Will not fix",
      "package_name": "python-paramiko",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2022-03-18T00:00:00Z",
  "bugzilla": {
    "description": "python-paramiko: Race condition in the write_private_key_file function",
    "id": "2065665",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2065665"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.1",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-362",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-24302",
  "document_distribution": "",
  "details": [
    "In Paramiko before 2.10.1, a race condition (between creation and chmod) in the write_private_key_file function could allow unauthorized information disclosure.",
    "A race condition was found in Paramiko. This flaw allows unauthorized information disclosure from an attacker with access to the write_private_key_file."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-24302\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-24302\nhttps://github.com/paramiko/paramiko/releases/tag/2.10.1"
  ]
}